Adds latest adb files. Installer now opens WSASettings and Installs Magisk.apk with minimal input from user.
LSPosed/MagiskOnWSA pull request #89
Opened 2021-11-16 06:09 UTC by okibcn

In order to complete the installation:
- The Workflow now downloads and adds the adb files from the latest Android Platform Tools
- In Magisk is selected, the powershell installation script now:
      a) Opens WSA Settings app
      b) Asks user to activate Developers settings and open Developers settings
      c) Sideloads Magisk.apk
      d) Opens Magisk App to complete Magisk installation.

2021-11-17 07:01 UTC, yujincheng08 requested changes

2021-11-17 07:01 UTC, yujincheng08 commented on .github/workflows/magisk.yml
> +              ./adb connect localhost:58526
if you could enable the dev mode of wsa automatically, you can launch a process of wsa and adb wait-for-device so that  we dont need to ask user to press enter.

2021-11-17 07:01 UTC, yujincheng08 commented on .github/workflows/magisk.yml
> +              Start-Sleep -s 5
I dont think the sleep is required. and why not launch magisk from adb?

2021-11-17 15:36 UTC, ahmadgtr786 commented on .github/workflows/magisk.yml
> +          unzip adb.zip
```suggestion
          unzip adb.zip
```

2021-11-17 15:43 UTC, okibcn commented on .github/workflows/magisk.yml
> +              Start-Sleep -s 5
Yes, you can launch Magisk from adb if you want. This method works fine and it is the standard way Windows executes installed Apps without adb. So I use adb only in those cases where adb is really required.

2021-11-17 15:53 UTC, okibcn commented on .github/workflows/magisk.yml
>            Add-AppxPackage -Register .\AppxManifest.xml
It would be nice having a completely silent installation. Maybe that setting is saved in the registry or in a config file, in a place we could modify. But I haven't figured out yet how to overcome this annoying step.

2021-11-17 15:56 UTC, yujincheng08 commented on .github/workflows/magisk.yml
>            Add-AppxPackage -Register .\AppxManifest.xml
Try it from https://stackoverflow.com/questions/40033608/enable-windows-10-developer-mode-programmatically
```powershell
# Create AppModelUnlock if it doesn't exist, required for enabling Developer Mode
$RegistryKeyPath = "HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\AppModelUnlock"
if (-not(Test-Path -Path $RegistryKeyPath)) {
    New-Item -Path $RegistryKeyPath -ItemType Directory -Force
}

# Add registry value to enable Developer Mode
New-ItemProperty -Path $RegistryKeyPath -Name AllowDevelopmentWithoutDevLicense -PropertyType DWORD -Value 1 -Force
```

2021-11-17 15:58 UTC, yujincheng08 commented on .github/workflows/magisk.yml
>            Add-AppxPackage -Register .\AppxManifest.xml
But ways to set the dev mode of wsa is still unknown.

2021-11-17 16:06 UTC, yujincheng08 commented on .github/workflows/magisk.yml
>            Add-AppxPackage -Register .\AppxManifest.xml
BTW, I found `%LOCALAPPDATA%\Packages\MicrosoftCorporationII.WindowsSubsystemForAndroid_8wekyb3d8bbwe\Settings\settings.dat` and it should be the configuration.

2021-11-17 16:08 UTC, yujincheng08 commented on .github/workflows/magisk.yml
>            Add-AppxPackage -Register .\AppxManifest.xml
And we can load it by regedit and see `LocalState\DeveloperModeEnabled`

2021-11-17 16:11 UTC, yujincheng08 commented on .github/workflows/magisk.yml
>            Add-AppxPackage -Register .\AppxManifest.xml
When it's enabled, its value is `0x0101AC006ECDDBD701`
And when it's disabled, its value is `0x00D311CD9FCDDBD701`

2021-11-17 18:57 UTC, okibcn commented on .github/workflows/magisk.yml
> +              ./adb connect localhost:58526
adb wait-for-device doesn't work with tcpip connections. However, it can try to connect and retry until the user enables developers mode from WSA Settings and opens an app.

2021-11-18 16:13 UTC, okibcn commented on .github/workflows/magisk.yml
> +          unzip adb.zip
It has to be copied to two folders, so unzip from pipe is not going to help. See the last changes, I only extract the three required files, copy them to the right folders, and cleanup the files.

2021-11-18 16:14 UTC, okibcn commented on .github/workflows/magisk.yml
> +              ./adb connect localhost:58526
I have implemented the wait to connect. please see recent commits to this PR.

2021-11-18 16:25 UTC, azeddinechaouch commented
mini

2021-11-18 22:11 UTC, okibcn commented on .github/workflows/magisk.yml
>            Add-AppxPackage -Register .\AppxManifest.xml
I am now working on this issue, The enable/disable state of DeveloperModeEnabled value is different in my system:
When enabled 01 7f 60 9e 21 c3 dc d7 01
When disabled 00 5f ef fc ac c5 dc d7 01

I have tested by modifying only the first byte from 00 to 01 and that makes the trick. This means that most probably we could do all the Magisk installation without user interaction. This opens the door to further customization during install.

2021-11-19 06:47 UTC, yujincheng08 commented
Seems awesome. I think we only need `AllowDevelopmentWithoutDevLicense` for the last step now.

2021-11-19 07:16 UTC, okibcn commented on .github/workflows/magisk.yml
>            Add-AppxPackage -Register .\AppxManifest.xml
Powershell installer now does a completely unattended installation.
The installer automatically activates Android developer mode, boots the system, and install Magisk if it has been selected. As a bonus, it disables sending diagnostics information for a completely silent installation.
 The only thing not yet implemented is to automatically activate Developers mode in Windows 11. Working on it now.

2021-11-19 07:33 UTC, okibcn commented on .github/workflows/magisk.yml
>            Add-AppxPackage -Register .\AppxManifest.xml
Windows 11 developers mode is now also part of the script. The conversation is resolved.

2021-11-19 12:57 UTC, yujincheng08 approved these changes

2021-11-19 12:58 UTC, merged

2021-11-20 00:39 UTC, ValZapod commented
Can you add amazon store preview appx somewhere? You can backup it with appx backup. https://github.com/mjmeans/Appx-Backup/issues

There is only a fake app on russian online appx downloader. Thank you :)

2021-11-20 00:47 UTC, okibcn commented
@ValZapod 
The apk is included in the package. If you only want the com.amazon.venezia apk, you can easily extract it from WSA. No need for using the APPX-BACKUP script.

2021-11-20 00:51 UTC, ValZapod commented
> apk is included in this WSA package. If you only want the com.amazon.venezia apk,

Oh, so it is actually 28 Mbyte apk file, right? This deep link that open the Microsft Store app: http://aka.ms/AmazonAppstore

Ha, wow.