Updated CI name & Magisk, ADB root solution check
LSPosed/MagiskOnWSA pull request #95
Opened 2021-11-19 17:21 UTC by pazhanir

Updated the runner name to easy of use
added root solution check to download magisk and adb

2021-11-19 18:02 UTC, okibcn approved these changes

2021-11-20 06:51 UTC, yujincheng08 requested changes

2021-11-20 06:51 UTC, yujincheng08 commented on .github/workflows/magisk.yml
> +        if: ${{ github.event.inputs.root_sol == 'magisk' || github.event.inputs.root_sol == '' }}
Magisk has to be downloaded for patching sepolicy.

2021-11-20 10:21 UTC, yujincheng08 approved these changes

2021-11-20 10:21 UTC, merged